version: '3'
services:
  flask:
    build: ./webapp
    container_name: devops_flask_proj
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True 
    restart: on-failure
    volumes:
      - ./webapp:/webapp
    ports:
      - "5000:5000"
    command: app.py
