version: '3'
services:
  flask:
    build: ./app
    container_name: devops_flask_proj
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True 
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python app.py
