version: '3'
services:
  flask:
    build: ./webapp
    container_name: devops_flask_proj
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True 
    restart: on-failure
    volumes:
      - ./webapp:/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: app.py

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
